words:
  - Naruto
  - One Piece
  - Dragon Ball
  - Attack on Titan
  - My Hero Academia
  - Death Note
  - Fullmetal Alchemist
  - Sword Art Online
  - Demon Slayer
  - One Punch Man
  - Tokyo Ghoul
  - Bleach
  - Cowboy Bebop
  - Neon Genesis Evangelion
  - Hunter x Hunter
  - JoJo's Bizarre Adventure
  - Pokémon
  - Fairy Tail
  - Black Clover
  - Naruto Shippuden
  - Dragon Ball Z
  - Code Geass
  - Steins;Gate
  - Re:Zero
  - Evangelion
  - Sailor Moon
  - Violet Evergarden
  - Gurren Lagann
  - Your Lie in April
  - Mob Psycho 100
  - Berserk
  - Promised Neverland
  - Haikyuu!!
  - Assassination Classroom
  - Food Wars!
  - Darling in the Franxx
  - Made in Abyss
  - Akame ga Kill!
  - Soul Eater
  - Tokyo Ghoul:re
  - My Neighbor Totoro
  - Kiki's Delivery Service
  - Howl's Moving Castle
  - Spirited Away
  - Princess Mononoke
  - Grave of the Fireflies
  - Nausicaä of the Valley of the Wind
  - Castle in the Sky
  - Ponyo
  - The Wind Rises
  - Whisper of the Heart
  - The Cat Returns
  - Porco Rosso
  - Only Yesterday
  - Pom Poko
  - Ocean Waves
  - Tales from Earthsea
  - The Tale of the Princess Kaguya
  - When Marnie Was There
  - Wolf Children
  - Summer Wars
  - The Girl Who Leapt Through Time
  - Boku no Pico
  - Rascal Does Not Dream
  - Eromanga Sensei
  - Tonikaku Kawaii
  - Clannad
  - Noragami
  - Great Teacher Onizuka
  - Hellsing
  - March Comes in Like a Lion
  - K-On!
  - Log Horizon
  - Anohana
  - Parasyte
  - Black Lagoon
  - Elfen Lied
  - Gintama
  - Nana
  - Angel Beats!
  - D.Gray-man
  - Outlaw Star
  - Mushishi
  - Durarara!!
  - Kakegurui
  - Yuri!!! on ICE
  - Haruhi Suzumiya no Yuuutsu
  - ReLIFE
  - Tsukimonogatari
  - Guilty Crown
  - Zombieland Saga
  - Wotakoi
  - Cautious Hero
  - Psycho-Pass
  - Maid-Sama!
  - Kiznaiver
  - Hinamatsuri
  - Kekkai Sensen (Blood Blockade Battlefront)
  - Yona of the Dawn
  - Tari Tari
  - Hitori Bocchi no Marumaru Seikatsu
  - Made in Abyss
  - Re:Creators
  - Baccano!
  - KonoSuba
  - The Rising of the Shield Hero
  - Great Pretender
  - Land of the Lustrous
  - The Promised Neverland
  - March Comes in Like a Lion
  - Sakamichi no Apollon (Kids on the Slope)
  - Tengen Toppa Gurren Lagann
  - Sakura Quest
  - Shouwa Genroku Rakugo Shinjuu
  - Monogatari Series
  - Hoshino Samidare
  - Nodame Cantabile
  - Hitori Bocchi no Marumaru Seikatsu
  - Kaze no Tani no Naushika (Nausicaä of the Valley of the Wind)
  - Bunny Drop
  - Hinamatsuri
  - Natsume’s Book of Friends
  - Kimi ni Todoke
  - Anohana
  - Sakura Trick
  - Hakata Tonkotsu Ramens
  - The Tatami Galaxy
  - Tatami Galaxy
  - Mushishi
  - Shingeki no Kyojin (Attack on Titan)
  - Chihayafuru
  - Kimi ni Todoke
  - The Ancient Magus' Bride
  - Nana
  - Higurashi When They Cry